version: 2

defaults: &defaults
  working_directory: "/docker/project"
  docker:
  - image: blockmason/dotnet:2.2

workflows:
  version: 2
  default:
    jobs:
    - build:
        requires:
        - initialize
    - initialize
    - test:
        requires:
        - build

jobs:
  initialize:
    <<: *defaults
    steps:
    - checkout
    - persist_to_workspace:
        root: /docker
        paths:
        - project
  build:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /docker
    - run:
        name: Building sources
        command: dotnet publish --configuration Release Blockmason.Link/Blockmason.Link.csproj
    - persist_to_workspace:
        root: /docker
        paths:
        - project/Blockmason.Link/obj
        - project/Blockmason.Link/bin
  test:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /docker
    - run:
        name: Testing
        command: |
          dotnet test --logger trx Blockmason.Link.Tests/Blockmason.Link.Tests.csproj
          find . -type f -name '*.trx' | xargs /docker/.dotnet/tools/trx2junit --output Blockmason.Link.Tests/TestResults/junit
          mv $(find Blockmason.Link.Tests/TestResults -type f -name '*.xml' | xargs) Blockmason.Link.Tests/TestResults/junit/results.xml
    - store_test_results:
        path: Blockmason.Link.Tests/TestResults
